name: Deploy swot-sitemap

env:
  FILENAME_PREFIX: sitemap
  FILENAME_EXTENSION: xml

on:
 workflow_dispatch:
 

jobs:
  generate-filename-suffix:
    runs-on: ubuntu-latest

    steps:    
      - name: Generate Timestamp
        id: generated-timestamp
        shell: bash
        run: |
            timestamp=$(date +'%Y%m%d.%H%M%S');
            echo "$timestamp";
            echo "value=$timestamp" >> $GITHUB_OUTPUT;
            
      - name: print details
        id: printed_details
        with:
          generated-timestamp: ${{ steps.generated-timestamp.outputs.value }}        
        shell: bash    
        run: |
          echo "filename_suffix = ${{ steps.generated-timestamp.outputs.value }}";