name: Deploy swot-sitemap

env:
  FILENAME: sitemap.xml
  FILE_LOCATION: ./swot-sitemap

on:
 workflow_dispatch:
 

jobs:
  generate-filename:
    runs-on: ubuntu-latest
    outputs:
      release_filename: ${{ steps.filename.outputs.value }}
    steps:    
      - name: Generate Timestamp
        id: generated_timestamp
        shell: bash
        run: |
            timestamp=$(date +'%Y%m%d-%H%M%S');
            echo "value=$timestamp" >> $GITHUB_OUTPUT;

      - name: Build Release Filename
        id: filename        
        shell: bash
        run: |
            suffix="${{ steps.generated_timestamp.outputs.value }}";
            prefix="${FILENAME%.*}";
            extension="${FILENAME##*.}"            
            echo "value=$prefix-$suffix.$extension" >> $GITHUB_OUTPUT;

  create-release-sitemap:
    needs: [generate-filename]
    runs-on: ubuntu-latest
    steps:    

      - name: Checkout this repository
        uses: actions/checkout@v3  

      - name: Make staging directory
        shell: bash
        run: sudo mkdir -p /staging
      
      - name: Copy sitemap.xml from source to staging
        id: staged_artifacts
        shell: bash
        run: |
          sudo cp ${FILE_LOCATION}/${FILENAME} /staging/${{ needs.generate-filename.outputs.release_filename }};
          # ls -l /staging;
          # cat /staging/${{ needs.generate-filename.outputs.release_filename }};

            
  print-details:
    needs: [generate-filename]
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        id: printed_details
        shell: bash
        run: |
          echo "FILENAME = $FILENAME";
          #echo "FILENAME_EXTENSION = $FILENAME_EXTENSION";
          echo "release_filename = ${{ needs.generate-filename.outputs.release_filename }}";